#!/usr/bin/env python3
"""Write the compiled-in local-data table (docs/design.md section 17) from a configuration file.

    python3 tests/gen_local.py <local.conf> [<out.cho>]

Each line is one directive: `record <name> <type> <value>`, `override <name> <type> <value>`, `block <name>` or
`block <name> <address>`. Blank lines and `#` comments are skipped. At most 512 directives, a name of at most 255
bytes, a value of at most 255 bytes. Two directives that match the same name and type are a tie and refused with file
and line, because a silent precedence would be a lie. The output is one static string of decimal byte fields that
`src/local.cho` parses once at start; the sorts it here are the matching rule: longest suffix first, a concrete name
before the wildcard that also matches it.
"""
import ipaddress, re, sys

HEAD = """edition 5;

module localtab;

// `localtab` -- the local records, overrides and blocklists this binary answers from (docs/design.md section 17).
// Generated by `tests/gen_local.py` from the configuration; do not edit by hand.

pub fn count() -> [] int {
    return %d;
}

pub fn text() -> [] &static [byte] {
    return "%s";
}
"""

RECORD, OVERRIDE, BLOCK_NX, BLOCK_A = 0, 1, 2, 3
TYPES = {"A": 1, "CNAME": 5, "PTR": 12, "MX": 15, "TXT": 16, "AAAA": 28, "SRV": 33}
MAX_DIRECTIVES, MAX_NAME, MAX_VALUE = 512, 255, 255


class Bad(Exception):
    pass


def fail(path, n, tag, line):
    raise Bad("%s:%d: %s: %r" % (path, n, tag, line))


def wire_name(name, path, n):
    """A domain name as DNS wire bytes: a length byte per label. A leading `*.` is kept as a label of one byte."""
    if len(name) > MAX_NAME:
        fail(path, n, "local-name-too-long", name)
    out = []
    for label in name.rstrip(".").split("."):
        if not 0 < len(label) < 64:
            fail(path, n, "local-name-too-long", name)
        out.append(len(label))
        out.extend(ord(c) for c in label.lower())
    out.append(0)
    return out


def text_name(name, path, n):
    return "".join(chr(b) for b in wire_name(name, path, n))


def encode(kind, name, rtype, value, path, n):
    """The rdata bytes of one directive, or the address of a block."""
    if kind in (RECORD, OVERRIDE):
        if rtype == 1:
            try:
                ip = ipaddress.IPv4Address(value)
            except ValueError:
                fail(path, n, "local-bad-value", value)
            return list(ip.packed)
        if rtype == 28:
            try:
                ip = ipaddress.IPv6Address(value)
            except ValueError:
                fail(path, n, "local-bad-value", value)
            return list(ip.packed)
        if rtype in (5, 12):
            return wire_name(value, path, n)
        if rtype == 16:
            if len(value) > 254 or not all(32 <= ord(c) <= 126 for c in value):
                fail(path, n, "local-value-too-long", value)
            return [len(value)] + [ord(c) for c in value]
        if rtype == 15:
            parts = value.split()
            if len(parts) != 2 or not parts[0].isdigit() or int(parts[0]) > 65535:
                fail(path, n, "local-bad-value", value)
            return [int(parts[0]) // 256, int(parts[0]) % 256] + wire_name(parts[1], path, n)
        if rtype == 33:
            parts = value.split()
            if len(parts) != 4 or any(not p.isdigit() or int(p) > 65535 for p in parts[:3]):
                fail(path, n, "local-bad-value", value)
            nums = [int(p) for p in parts[:3]]
            out = []
            for v in nums:
                out.extend([v // 256, v % 256])
            return out + wire_name(parts[3], path, n)
    if kind == BLOCK_A:
        try:
            return list(ipaddress.IPv4Address(value).packed)
        except ValueError:
            fail(path, n, "local-bad-value", value)
    return []


def read(path):
    out = []
    for n, line in enumerate(open(path), 1):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split(None, 1)
        kind = parts[0]
        if kind not in ("record", "override", "block"):
            fail(path, n, "local-bad-type", line)
        rest = parts[1].split()
        if kind in ("record", "override"):
            if len(rest) < 3 or rest[1].upper() not in TYPES:
                fail(path, n, "local-bad-type", line)
            name, rtype = rest[0], TYPES[rest[1].upper()]
            value = " ".join(rest[2:])
            if len(value) > MAX_VALUE:
                fail(path, n, "local-value-too-long", value)
            k = RECORD if kind == "record" else OVERRIDE
        else:
            name = rest[0]
            if len(rest) == 1:
                k, rtype, value = BLOCK_NX, 0, ""
            elif len(rest) == 2:
                k, rtype, value = BLOCK_A, 0, rest[1]
            else:
                fail(path, n, "local-bad-value", line)
        out.append((k, rtype, name, encode(k, name, rtype, value, path, n), n))
    if len(out) > MAX_DIRECTIVES:
        raise Bad("%s: %d directives; at most %d" % (path, len(out), MAX_DIRECTIVES))
    return out


def sort_key(directive):
    kind, rtype, name, _, _n = directive
    labels = name.rstrip(".").split(".")
    wild = 1 if labels[0] == "*" else 0
    # Longest suffix first: more concrete labels, then a longer name, then no wildcard before one.
    return (-len(labels), -len(name), wild, name.lower())


def pattern_labels(name):
    return name.rstrip(".").split(".")


def tie_check(directives, path):
    """Two directives that can both match the same query name and type are a tie, refused at generation. An exact name
    beats a wildcard (it is more specific, and the rule is deterministic), so only these are ties: two directives of the
    same shape (both exact, or both wildcards of overlapping suffix) at overlapping types. A `block` (type 0) overlaps
    every type."""
    for i, (k1, t1, n1, _, l1) in enumerate(directives):
        for j, (k2, t2, n2, _, l2) in enumerate(directives[i + 1:], i + 1):
            if t1 != t2 and t1 != 0 and t2 != 0:
                continue
            a1, a2 = pattern_labels(n1), pattern_labels(n2)
            if (a1[0] == "*") != (a2[0] == "*"):
                continue
            if a1[0] == "*":
                s1, s2 = a1[1:], a2[1:]
                if s1 == s2 or s1[len(s1) - len(s2):] == s2 or s2[len(s2) - len(s1):] == s1:
                    raise Bad("%s: local-tie: %s (line %d) and %s (line %d)" % (path, n1, l1, n2, l2))
            elif a1 == a2:
                raise Bad("%s: local-tie: %s (line %d) and %s (line %d)" % (path, n1, l1, n2, l2))


def render(directives):
    lines = []
    for kind, rtype, name, rdata, _n in directives:
        nw = wire_name(name, "render", 0)
        fields = [kind, rtype, len(nw), len(rdata)] + nw + rdata
        lines.append(" ".join(str(f) for f in fields))
    text = "\\n".join(lines) + "\\n" if lines else ""
    return HEAD % (len(directives), text)


if __name__ == "__main__":
    try:
        directives = sorted(read(sys.argv[1]), key=sort_key)
        tie_check(directives, sys.argv[1])
        rendered = render(directives)
    except Bad as e:
        sys.exit(str(e))
    if len(sys.argv) > 2:
        open(sys.argv[2], "w").write(rendered)
    else:
        sys.stdout.write(rendered)
