#!/usr/bin/env python3
"""Write the compiled-in upstream table (docs/design.md sections 3 and 15) from a configuration file.

    python3 tests/gen_upstreams.py <upstreams.conf> [<out.cho>]

Each line of the configuration is `<ipv4 address> <port>`; blank lines and `#` comments are skipped. At most 8 upstreams. A line that
is not an address and a port is refused with its line number rather than skipped, because the file is the whole of what the binary
may reach.
"""
import re, sys

HEAD = '''edition 5;

module upstreams;

// `upstreams` -- the upstream resolvers this binary may forward to, compiled in (`docs/design.md` section 3). Generated by
// `tests/gen_upstreams.py` from the configuration below; do not edit by hand.

'''


def read(path):
    out = []
    for n, line in enumerate(open(path), 1):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        m = re.fullmatch(r"(\d{1,3}(?:\.\d{1,3}){3})\s+(\d{1,5})", line)
        if not m or any(int(o) > 255 for o in m.group(1).split(".")) or not 0 < int(m.group(2)) < 65536:
            sys.exit("%s:%d: not '<ipv4 address> <port>': %r" % (path, n, line))
        out.append((m.group(1), int(m.group(2))))
    if len(out) > 8:
        sys.exit("%s: %d upstreams; at most 8" % (path, len(out)))
    return out


def render(ups):
    s = HEAD
    s += "pub fn count() -> [] int {\n    return %d;\n}\n\n" % len(ups)
    s += "pub fn host(i: int) -> [] &static [byte] {\n"
    for i, (h, _) in enumerate(ups):
        s += '    if i == %d {\n        return "%s";\n    }\n' % (i, h)
    s += '    return "";\n}\n\n'
    s += "pub fn port(i: int) -> [] int {\n"
    for i, (_, p) in enumerate(ups):
        s += "    if i == %d {\n        return %d;\n    }\n" % (i, p)
    s += "    return 0;\n}\n"
    return s


if __name__ == "__main__":
    ups = read(sys.argv[1])
    text = render(ups)
    if len(sys.argv) > 2:
        open(sys.argv[2], "w").write(text)
    else:
        sys.stdout.write(text)
