#!/usr/bin/env python3
"""Write the compiled-in access list (docs/design.md section 16) from a configuration file.

    python3 tests/gen_access.py <access.conf> [<out.cho>]

Each line is `allow <ipv4 address>/<length>`; blank lines and `#` comments are skipped. At most 16 prefixes. A line that is anything
else is refused with its line number, because the file is the whole of whom the binary serves. The host bits of an address are
cleared (`10.1.2.3/8` is `10.0.0.0/8`), and said so, rather than kept to confuse a later reader.
"""
import re, sys

HEAD = '''edition 5;

module access;

// `access` -- the networks this binary serves, compiled in (`docs/design.md` section 16). Generated by `tests/gen_access.py` from
// the configuration; do not edit by hand. A client outside every prefix is refused.

'''


def read(path):
    out = []
    for n, line in enumerate(open(path), 1):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        m = re.fullmatch(r"allow\s+(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})", line)
        if not m or any(int(m.group(i)) > 255 for i in range(1, 5)) or int(m.group(5)) > 32:
            sys.exit("%s:%d: not 'allow <ipv4 address>/<length>': %r" % (path, n, line))
        addr = sum(int(m.group(i + 1)) << (24 - 8 * i) for i in range(4))
        length = int(m.group(5))
        mask = (0xFFFFFFFF << (32 - length)) & 0xFFFFFFFF if length else 0
        if addr & ~mask & 0xFFFFFFFF:
            print("%s:%d: host bits of %s cleared (the prefix is %d.%d.%d.%d/%d)" % (
                path, n, line.split()[1], *(((addr & mask) >> s) & 255 for s in (24, 16, 8, 0)), length), file=sys.stderr)
        out.append((addr & mask, mask))
    if len(out) > 16:
        sys.exit("%s: %d prefixes; at most 16" % (path, len(out)))
    return out


def render(prefixes):
    s = HEAD
    s += "pub fn count() -> [] int {\n    return %d;\n}\n\n" % len(prefixes)
    s += "pub fn network(i: int) -> [] int {\n"
    for i, (a, _) in enumerate(prefixes):
        s += "    if i == %d {\n        return %d;\n    }\n" % (i, a)
    s += "    return 0;\n}\n\n"
    s += "pub fn mask(i: int) -> [] int {\n"
    for i, (_, m) in enumerate(prefixes):
        s += "    if i == %d {\n        return %d;\n    }\n" % (i, m)
    s += "    return 0;\n}\n\n"
    s += '''// Does the IPv4 address `address` (a 32-bit number, first octet highest) fall inside a prefix?
pub fn allowed(address: int) -> [] bool {
    var i = 0;
    while i < count() {
        if address & mask(i) == network(i) {
            return true;
        }
        i = i + 1;
    }
    return false;
}
'''
    return s


if __name__ == "__main__":
    text = render(read(sys.argv[1]))
    if len(sys.argv) > 2:
        open(sys.argv[2], "w").write(text)
    else:
        sys.stdout.write(text)
